(function() {var implementors = {};
implementors['semver'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='semver/enum.Identifier.html' title='semver::Identifier'>Identifier</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='semver/struct.Version.html' title='semver::Version'>Version</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='semver/enum.ParseError.html' title='semver::ParseError'>ParseError</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='semver/struct.VersionReq.html' title='semver::VersionReq'>VersionReq</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='semver/enum.ReqParseError.html' title='semver::ReqParseError'>ReqParseError</a>",];implementors['conduit'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='conduit/enum.Scheme.html' title='conduit::Scheme'>Scheme</a>","impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='conduit/enum.Host.html' title='conduit::Host'>Host</a>&lt;'a&gt;","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='conduit/enum.Method.html' title='conduit::Method'>Method</a>",];implementors['conduit_utils'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='conduit_utils/struct.HeaderMap.html' title='conduit_utils::HeaderMap'>HeaderMap</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
